#!/bin/zsh

exec ssh -t ${@} 'printf "\033[1;30m" && tmux ls 2>/dev/null || echo "no sessions" && printf "\033[0mEnter the name of the new or existing session: \033[1;36m" && read tmux_session && printf "\033[1;30m" && if tmux has-session -t ${tmux_session:-default}; then tmux -CC attach -t ${tmux_session:-default}; else tmux -CC new -s ${tmux_session:-default}; fi; sleep 1'